In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import Lasso, Ridge
import warnings
warnings.filterwarnings("ignore")

In [3]:
# df=pd.read_table("/content/cars (1).csv",sep=",")
df=pd.read_table("/content/cars.csv",sep=",")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB


In [5]:
df['normalized-losses'].replace("?",np.nan,inplace=True)
df['horsepower'].replace("?",np.nan,inplace=True)

In [6]:
si=SimpleImputer(missing_values=np.nan,strategy='mean')
df[['normalized-losses','horsepower']]=si.fit_transform(df[['normalized-losses','horsepower']])

In [7]:
df['normalized-losses'].value_counts()

,count
normalized-losses,
122.0,45
161.0,11
91.0,8
150.0,7
128.0,6
104.0,6
134.0,6
103.0,5
168.0,5


We need to handly categorical columns

In [8]:
df.select_dtypes(object)

,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,alfa-romero,gas,convertible,rwd,front,dohc
1,alfa-romero,gas,convertible,rwd,front,dohc
2,alfa-romero,gas,hatchback,rwd,front,ohcv
3,audi,gas,sedan,fwd,front,ohc
4,audi,gas,sedan,4wd,front,ohc
...,...,...,...,...,...,...
200,volvo,gas,sedan,rwd,front,ohc
201,volvo,gas,sedan,rwd,front,ohc
202,volvo,gas,sedan,rwd,front,ohcv
203,volvo,diesel,sedan,rwd,front,ohc


In [9]:
catcol=df.select_dtypes(object).columns
catcol

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [10]:
oe= OrdinalEncoder()
df[catcol]=oe.fit_transform(df[catcol])

In [11]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,122.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28,16845
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25,19045
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23,21485
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27,22470


In [12]:
X=df.iloc[ : , :-1]
Y=df.iloc[ : ,-1]

In [13]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.3,random_state=1)

In [14]:
linreg=LinearRegression()
linreg.fit(xtrain, ytrain)
y_pred=linreg.predict(xtest)

In [15]:
r2=r2_score(ytest,y_pred)
print(f"r2: {r2}")

r2: 0.796556678039738


In [16]:
train=linreg.score(xtrain,ytrain)
test=linreg.score(xtest,ytest)
print(f"train result: {train}")
print(f"test result: {test}")

train result: 0.8504573774895473
test result: 0.796556678039738


1.low traning error mean low bias
2.low acouse in testing error is
3.low bias and high variance is give you to overfiting

In [18]:
L1=Lasso(alpha=169)
L1.fit(xtrain,ytrain)
Y_pred=L1.predict(xtest)
train=L1.score(xtrain,ytrain)
test=L1.score(xtest,ytest)
r2=r2_score(ytest,y_pred)
print(f"train result: {train}")
print(f"test result: {test}")
print(f"r2: {round(r2,2)}")

train result: 0.8134398734696936
test result: 0.8132785388258221
r2: 0.8


In [17]:
L2=Ridge(alpha=169)
L2.fit(xtrain,ytrain)
Y_pred=L2.predict(xtest)
train=L2.score(xtrain,ytrain)
test=L2.score(xtest,ytest)
r2=r2_score(ytest,y_pred)
print(f"train result: {train}")
print(f"test result: {test}")
print(f"r2: {round(r2,2)}")

train result: 0.7767954382793328
test result: 0.8048104350962467
r2: 0.8


## Explanation of R-squared (R2 Score)

R-squared, also known as the coefficient of determination, is a statistical measure that represents the proportion of the variance in the dependent variable that can be explained by the independent variables in a regression model.

### What does R-squared tell us?

*   **How well the model fits the data**: R-squared ranges from 0 to 1 (or 0% to 100%).
    *   **0%**: Indicates that the model explains none of the variability of the response data around its mean.
    *   **100%**: Indicates that the model explains all the variability of the response data around its mean.
*   **Goodness of fit**: A higher R-squared value generally indicates a better fit for the model, meaning that more of the variation in the dependent variable can be explained by the independent variables included in your model.

### Why is it important?

1.  **Model Performance**: It helps in understanding how much of the variation in the target variable (in your case, 'price') is captured by your model. For instance, an R-squared of 0.8 means that 80% of the variation in car prices can be explained by the features in your dataset, while the remaining 20% is due to unexplained variability or other factors not included in the model.
2.  **Comparison**: It's often used to compare different regression models. If you have two models, the one with the higher R-squared is generally considered to be a better fit for the data.
3.  **Predictive Power**: While a high R-squared doesn't necessarily mean the model is good for prediction (as it can be inflated by adding more variables, even irrelevant ones), it does give an initial indication of the model's explanatory power.

**In your output, an `r2` score of approximately `0.8` (or 80%) for both Linear Regression, Lasso, and Ridge models suggests that these models can explain about 80% of the variance in car prices based on the features you've provided.**

In [19]:
linreg.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [20]:
L1.coef_

array([ 4.69984023e+00,  1.99632535e+00, -1.72221126e+02, -0.00000000e+00,
       -3.68828572e+02,  1.23866762e+03,  4.35113307e+03,  4.02198115e+02,
        4.53320466e+02,  3.01054481e+02,  1.13016944e+02,  1.01237908e+01,
        8.18884778e+01, -1.71406319e+02])

In [21]:
L2.coef_

array([  91.61511852,    3.55001032, -158.39433405, -142.42786351,
       -226.50794447,  307.1085788 ,  196.49594781,  243.60290611,
        406.33101126,  212.96358331,  121.627826  ,   20.03512196,
         79.90433856, -170.58624083])

hyper parameter turning

In [22]:
for i in range(150,200):
  L1=Lasso(alpha=i)
  L1.fit(xtrain,ytrain)
  Y_pred=L1.predict(xtest)
  train=L1.score(xtrain,ytrain)
  test=L1.score(xtest,ytest)
  r2=r2_score(ytest,y_pred)

  print(f"alpha: {i}    train result: {train}   test result: {test}    r2: {round(r2,2)}")


alpha: 150    train result: 0.8212288879856349   test result: 0.8124969899539802    r2: 0.8
alpha: 151    train result: 0.8208421468238061   test result: 0.8125456274822552    r2: 0.8
alpha: 152    train result: 0.8204526518423789   test result: 0.8125934728624998    r2: 0.8
alpha: 153    train result: 0.8200607762157636   test result: 0.8126404383406126    r2: 0.8
alpha: 154    train result: 0.8196661304388356   test result: 0.8126866131583909    r2: 0.8
alpha: 155    train result: 0.8192691148773523   test result: 0.812731907864298    r2: 0.8
alpha: 156    train result: 0.8188695301369727   test result: 0.8127763675886549    r2: 0.8
alpha: 157    train result: 0.818467171522371   test result: 0.8128200339758355    r2: 0.8
alpha: 158    train result: 0.818062449862035   test result: 0.8128628223230776    r2: 0.8
alpha: 159    train result: 0.8176549464501084   test result: 0.8129048166168775    r2: 0.8
alpha: 160    train result: 0.8172450881050913   test result: 0.8129459336049878   